--liquibase formatted sql
--changeset fff:2
CREATE TABLE IF NOT EXISTS public.rates
(
    id      integer                                            NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    rate    double precision                                   NOT NULL,
    date    character varying(12) COLLATE pg_catalog."default" NOT NULL,
    curr_id integer                                            NOT NULL,
    CONSTRAINT rates_pkey PRIMARY KEY (id),
    CONSTRAINT date_rate UNIQUE (date, rate),
    CONSTRAINT fk_currency FOREIGN KEY (curr_id)
        REFERENCES public.currencies (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
